FROM ghcr.io/lazka/msys2-mingw-base

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN \
  function msys() { C:\msys64\usr\bin\bash.exe @('-lc') + @Args; } \
  msys 'pacman -S --needed --noconfirm mingw-w64-i686-toolchain'; \
  msys 'pacman --noconfirm -Scc';
