name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-docker:

    runs-on: windows-2016
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build base image
        run: |
          Get-Content Dockerfile.msys2-base | docker build -t ghcr.io/lazka/msys2-base:ltsc2016 -

      - name: Build mingw image
        run: |
          Get-Content Dockerfile.msys2-mingw | docker build -t ghcr.io/lazka/msys2-mingw:ltsc2016 -

      - name: Test
        run: |
          docker run ghcr.io/lazka/msys2-base:ltsc2016 C:\msys64\usr\bin\bash.exe -lc "pacman --version"
          docker run ghcr.io/lazka/msys2-mingw:ltsc2016 C:\msys64\usr\bin\bash.exe -lc "pacman --version"

      - name: Log in
        if: github.ref == 'refs/heads/main'
        run: |
          echo "$env:TOKEN" | docker login ghcr.io --username "$env:USERNAME" --password-stdin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}

      - name: Deploy images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/lazka/msys2-base:ltsc2016
          docker push ghcr.io/lazka/msys2-mingw:ltsc2016